FROM python:3.13.2-slim-bookworm

ARG CELERY_BROKER_URL

RUN apt update && apt upgrade -y

WORKDIR /app

COPY worker/ .

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["celery", "-A", "tasks", "worker", "--loglevel=INFO"]
